#-------------------------------
# Site Settings
title: Dominic Belfiori
logo: # You can add own logo. For example '/images/logo.png'.
description: Norlin – A Beautiful Dark Blog Theme for Jekyll.


#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Experience'
      url: '/experience/'
    - title: 'Projects'
      url: '/projects/'
#-------------------------------
# Author Settings
author:
  name: Dominic Belfiori
  avatar: '/images/15.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Dominic Belfiori
  description: I am a multi-disciplinary developer with over 12 years experience working with Enterprise level companies on their Email Marketing Campaigns, Landing Pages, and Websites.
  image: '/images/01.jpg'


#-------------------------------
# Contact Settings
contact:
  email:  # Add your email for contact form
  description: # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
social:
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/in/dominicbelfiori/"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp-button-text: 